direction: right

aws_cloud: "AWS Cloud" {
  your_account: "Your account" {
    vpc1: "VPC 1" {
      instances1: Instances
    }
    vpc2: "VPC 2" {
      instances2: Instances
    }
  }

  third_party_account: "Third-party account" {
    vpc3: "VPC 3" {
      instances3: Instances
    }
    vpc4: "VPC 4" {
      instances4: Instances
    }
  }

  transit_gateway: "Transit Gateway"

  route_table: "Route table\n172.16.0.0\n172.16.1.0\n172.16.2.0"

  vpc1 -> transit_gateway
  vpc2 -> transit_gateway
  transit_gateway -> vpc3
  transit_gateway -> vpc4

  route_table -> transit_gateway
}
